<style type="text/css">
    #cloudiq-callme-button.<?php echo $this->_getTemplateClass(); ?> #cloudiq-callme-button-content,
    #cloudiq-callme-popup.<?php echo $this->_getTemplateClass(); ?> {
        background: -moz-linear-gradient(top,  #<?php echo $this->_getGradientStartColour(); ?> 0%, #<?php echo $this->_getGradientEndColour(); ?> 100%); /* FF3.6+ */
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#<?php echo $this->_getGradientStartColour(); ?>), color-stop(100%,#<?php echo $this->_getGradientEndColour(); ?>)); /* Chrome,Safari4+ */
        background: -webkit-linear-gradient(top,  #<?php echo $this->_getGradientStartColour(); ?> 0%,#<?php echo $this->_getGradientEndColour(); ?> 100%); /* Chrome10+,Safari5.1+ */
        background: -o-linear-gradient(top,  #<?php echo $this->_getGradientStartColour(); ?> 0%,#<?php echo $this->_getGradientEndColour(); ?> 100%); /* Opera 11.10+ */
        background: -ms-linear-gradient(top,  #<?php echo $this->_getGradientStartColour(); ?> 0%,#<?php echo $this->_getGradientEndColour(); ?> 100%); /* IE10+ */
        background: linear-gradient(to bottom,  #<?php echo $this->_getGradientStartColour(); ?> 0%,#<?php echo $this->_getGradientEndColour(); ?> 100%); /* W3C */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#<?php echo $this->_getGradientStartColour(); ?>', endColorstr='#<?php echo $this->_getGradientEndColour(); ?>',GradientType=0 ); /* IE6-8 */
        color: #<?php echo $this->_getContrastColourBW($this->_getColour()); ?>;
        border-color: #<?php echo $this->_getColour(); ?>;
    }
    #cloudiq-callme-popup.<?php echo $this->_getTemplateClass(); ?> button {
        background-color: #<?php echo $this->_getColour(); ?>;
        color: #<?php echo $this->_getContrastColourBW($this->_getColour()); ?>;
    }
</style>
<div id="cloudiq-callme-button" class="<?php echo $this->_getButtonClass(); ?>">
    <div id="cloudiq-callme-button-content">
        <p id="cloudiq-callme-button-title"><?php echo $this->_getFromConfig("button_heading"); ?></p>
        <p id="cloudiq-callme-button-message"><?php echo $this->_getFromConfig("button_message"); ?></p>
    </div>
</div>
<div id="cloudiq-callme-popup" class="<?php echo $this->_getPopupClass(); ?>">
    <div id="cloudiq-callme-popup-close">&times;</div>
    <?php if ($this->_getLogoUrl()) : ?>
        <img id="cloudiq-callme-popup-logo" src="<?php echo $this->_getLogoUrl(); ?>" alt="Logo" />
    <?php endif; ?>
    <p id="cloudiq-callme-popup-title"><?php echo $this->_getFromConfig("pop_up_title"); ?></p>
    <p id="cloudiq-callme-popup-strapline"><?php echo $this->_getFromConfig("pop_up_strapline"); ?></p>
    <form id="cloudiq-callme-popup-form" name="cloudiq-callme-popup-form" method="POST" action="<?php echo $this->_getFormUrl(); ?>">
        <label for="cloudiq-callme-popup-form-number"><?php echo $this->__("Mobile number (e.g. +44...)"); ?></label>
        <input type="text" name="phone_number" id="cloudiq-callme-popup-form-number" title="<?php echo $this->__("Please enter in international format, i.e. +44"); ?>" />
        <div id="cloudiq-callme-popup-response"></div>
        <button type="submit" id="cloudiq-callme-popup-form-button" <?php if ($this->getDisabled()) echo "disabled"; ?>>Submit</button>
    </form>
</div>
<script>cloudiqCallmeInit()</script>
